### ISSUE TITLE
I come up with a login screen. What do I do now?

### ISSUE THREAD

**Issue by ghost** [nwalters512/wildrank-android-v2#11]

**Comment by nwalters512** [comment]
You'll have to add a user with the desktop app. V2 requires a login in order to track who modifies data.

**Comment by ghost** [comment]
How would I do that?

**Comment by ghost** [comment]
I have V2 but I don't see a button for it.

**Comment by nwalters512** [comment]
I haven't run the desktop app in over a year and a half, so I forget the
exact flow. Now that we've released this for public use, we could stand to
document it better and make it more user-friendly.

That being said, there should be a pretty obvious button to add/manage
users.

**Comment by nwalters512** [comment]
I'm away from my laptop for the night, so I won't be able to open it. If
you post a screenshot of the desktop app, I might be able to help you
faster.

**Comment by ghost** [comment]
![capture8](https://cloud.githubusercontent.com/assets/17031883/18407901/d6de9c4a-76d2-11e6-98c2-6f6e0ee43aeb.PNG)

**Comment by ghost** [comment]
No button for it

**Comment by nwalters512** [comment]
Are you sure you cloned and ran from
https://github.com/wildstang/wildrank-desktop ?

**Comment by nkiel** [comment]
I presume you are using Eclipse so use the built in Git to clone then import this repo:
https://github.com/wildstang/wildrank-desktop

Run it as a Java Application then after you select your flash drive you get this

![wild rank v2](https://cloud.githubusercontent.com/assets/11053250/18407989/20c4de6a-76e6-11e6-9614-1436061b3ef5.jpg)

Click on "Write CSV" that will get you to beable to write in a user for yourself.

P.S. I think you are using an old version of the WildRank Desktop App

**Comment by nkiel** [comment]
I messed up you actually hit Manage Users then when your done with your account and what not Write CSV will finalize it on the Flash drive you selected earlier

Opps.....

**Comment by ghost** [comment]
I'm not, got from v2 repo, this one
